name: dart_js_improvements

environment:
  sdk: ">=2.0.0-dev <2.0.0"

dev_dependencies:
  dart_style:
  glob:
  js:
  jsbench:
  node_preamble:

transformers:
  - $dart2js:
      minify: true
      commandLineOptions:
          - --dump-info
          - --trust-type-annotations
          - --trust-primitives
